// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/billing_reader.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReceiptRequest) Reset() {
	*x = ReadReceiptRequest{}
	mi := &file_pb_billing_reader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceiptRequest) ProtoMessage() {}

func (x *ReadReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_billing_reader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceiptRequest.ProtoReflect.Descriptor instead.
func (*ReadReceiptRequest) Descriptor() ([]byte, []int) {
	return file_pb_billing_reader_proto_rawDescGZIP(), []int{0}
}

func (x *ReadReceiptRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type Receipt struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NameEdited       string                 `protobuf:"bytes,2,opt,name=name_edited,json=nameEdited,proto3" json:"name_edited,omitempty"`
	PurchasePrice    float64                `protobuf:"fixed64,3,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	PurchaseQuantity float64                `protobuf:"fixed64,4,opt,name=purchase_quantity,json=purchaseQuantity,proto3" json:"purchase_quantity,omitempty"`
	Remark           string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_pb_billing_reader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_pb_billing_reader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_pb_billing_reader_proto_rawDescGZIP(), []int{1}
}

func (x *Receipt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Receipt) GetNameEdited() string {
	if x != nil {
		return x.NameEdited
	}
	return ""
}

func (x *Receipt) GetPurchasePrice() float64 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *Receipt) GetPurchaseQuantity() float64 {
	if x != nil {
		return x.PurchaseQuantity
	}
	return 0
}

func (x *Receipt) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ReadReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Receipt       []*Receipt             `protobuf:"bytes,3,rep,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReceiptResponse) Reset() {
	*x = ReadReceiptResponse{}
	mi := &file_pb_billing_reader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceiptResponse) ProtoMessage() {}

func (x *ReadReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_billing_reader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceiptResponse.ProtoReflect.Descriptor instead.
func (*ReadReceiptResponse) Descriptor() ([]byte, []int) {
	return file_pb_billing_reader_proto_rawDescGZIP(), []int{2}
}

func (x *ReadReceiptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadReceiptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadReceiptResponse) GetReceipt() []*Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

var File_pb_billing_reader_proto protoreflect.FileDescriptor

const file_pb_billing_reader_proto_rawDesc = "" +
	"\n" +
	"\x17pb/billing_reader.proto\x12\x0fbillingReaderPb\"3\n" +
	"\x12ReadReceiptRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\"\xaa\x01\n" +
	"\aReceipt\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vname_edited\x18\x02 \x01(\tR\n" +
	"nameEdited\x12%\n" +
	"\x0epurchase_price\x18\x03 \x01(\x01R\rpurchasePrice\x12+\n" +
	"\x11purchase_quantity\x18\x04 \x01(\x01R\x10purchaseQuantity\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\"y\n" +
	"\x13ReadReceiptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x122\n" +
	"\areceipt\x18\x03 \x03(\v2\x18.billingReaderPb.ReceiptR\areceipt2i\n" +
	"\rBillingReader\x12X\n" +
	"\vReadReceipt\x12#.billingReaderPb.ReadReceiptRequest\x1a$.billingReaderPb.ReadReceiptResponseB$Z\"github.com/hifat/billing-reader/pbb\x06proto3"

var (
	file_pb_billing_reader_proto_rawDescOnce sync.Once
	file_pb_billing_reader_proto_rawDescData []byte
)

func file_pb_billing_reader_proto_rawDescGZIP() []byte {
	file_pb_billing_reader_proto_rawDescOnce.Do(func() {
		file_pb_billing_reader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_billing_reader_proto_rawDesc), len(file_pb_billing_reader_proto_rawDesc)))
	})
	return file_pb_billing_reader_proto_rawDescData
}

var file_pb_billing_reader_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_billing_reader_proto_goTypes = []any{
	(*ReadReceiptRequest)(nil),  // 0: billingReaderPb.ReadReceiptRequest
	(*Receipt)(nil),             // 1: billingReaderPb.Receipt
	(*ReadReceiptResponse)(nil), // 2: billingReaderPb.ReadReceiptResponse
}
var file_pb_billing_reader_proto_depIdxs = []int32{
	1, // 0: billingReaderPb.ReadReceiptResponse.receipt:type_name -> billingReaderPb.Receipt
	0, // 1: billingReaderPb.BillingReader.ReadReceipt:input_type -> billingReaderPb.ReadReceiptRequest
	2, // 2: billingReaderPb.BillingReader.ReadReceipt:output_type -> billingReaderPb.ReadReceiptResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_billing_reader_proto_init() }
func file_pb_billing_reader_proto_init() {
	if File_pb_billing_reader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_billing_reader_proto_rawDesc), len(file_pb_billing_reader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_billing_reader_proto_goTypes,
		DependencyIndexes: file_pb_billing_reader_proto_depIdxs,
		MessageInfos:      file_pb_billing_reader_proto_msgTypes,
	}.Build()
	File_pb_billing_reader_proto = out.File
	file_pb_billing_reader_proto_goTypes = nil
	file_pb_billing_reader_proto_depIdxs = nil
}
