// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: pb/billing_reader.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BillingReaderClient is the client API for BillingReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingReaderClient interface {
	ReadReceipt(ctx context.Context, opts ...grpc.CallOption) (BillingReader_ReadReceiptClient, error)
}

type billingReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingReaderClient(cc grpc.ClientConnInterface) BillingReaderClient {
	return &billingReaderClient{cc}
}

func (c *billingReaderClient) ReadReceipt(ctx context.Context, opts ...grpc.CallOption) (BillingReader_ReadReceiptClient, error) {
	stream, err := c.cc.NewStream(ctx, &BillingReader_ServiceDesc.Streams[0], "/billingReaderPb.BillingReader/ReadReceipt", opts...)
	if err != nil {
		return nil, err
	}
	x := &billingReaderReadReceiptClient{stream}
	return x, nil
}

type BillingReader_ReadReceiptClient interface {
	Send(*ReadReceiptRequest) error
	CloseAndRecv() (*ReadReceiptResponse, error)
	grpc.ClientStream
}

type billingReaderReadReceiptClient struct {
	grpc.ClientStream
}

func (x *billingReaderReadReceiptClient) Send(m *ReadReceiptRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *billingReaderReadReceiptClient) CloseAndRecv() (*ReadReceiptResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReadReceiptResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BillingReaderServer is the server API for BillingReader service.
// All implementations must embed UnimplementedBillingReaderServer
// for forward compatibility
type BillingReaderServer interface {
	ReadReceipt(BillingReader_ReadReceiptServer) error
	mustEmbedUnimplementedBillingReaderServer()
}

// UnimplementedBillingReaderServer must be embedded to have forward compatible implementations.
type UnimplementedBillingReaderServer struct {
}

func (UnimplementedBillingReaderServer) ReadReceipt(BillingReader_ReadReceiptServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadReceipt not implemented")
}
func (UnimplementedBillingReaderServer) mustEmbedUnimplementedBillingReaderServer() {}

// UnsafeBillingReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingReaderServer will
// result in compilation errors.
type UnsafeBillingReaderServer interface {
	mustEmbedUnimplementedBillingReaderServer()
}

func RegisterBillingReaderServer(s grpc.ServiceRegistrar, srv BillingReaderServer) {
	s.RegisterService(&BillingReader_ServiceDesc, srv)
}

func _BillingReader_ReadReceipt_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BillingReaderServer).ReadReceipt(&billingReaderReadReceiptServer{stream})
}

type BillingReader_ReadReceiptServer interface {
	SendAndClose(*ReadReceiptResponse) error
	Recv() (*ReadReceiptRequest, error)
	grpc.ServerStream
}

type billingReaderReadReceiptServer struct {
	grpc.ServerStream
}

func (x *billingReaderReadReceiptServer) SendAndClose(m *ReadReceiptResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *billingReaderReadReceiptServer) Recv() (*ReadReceiptRequest, error) {
	m := new(ReadReceiptRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BillingReader_ServiceDesc is the grpc.ServiceDesc for BillingReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billingReaderPb.BillingReader",
	HandlerType: (*BillingReaderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadReceipt",
			Handler:       _BillingReader_ReadReceipt_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pb/billing_reader.proto",
}
