// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: pb/billing_reader.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BillingReaderClient is the client API for BillingReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingReaderClient interface {
	ReadReceipt(ctx context.Context, in *ReadReceiptRequest, opts ...grpc.CallOption) (*ReadReceiptResponse, error)
}

type billingReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingReaderClient(cc grpc.ClientConnInterface) BillingReaderClient {
	return &billingReaderClient{cc}
}

func (c *billingReaderClient) ReadReceipt(ctx context.Context, in *ReadReceiptRequest, opts ...grpc.CallOption) (*ReadReceiptResponse, error) {
	out := new(ReadReceiptResponse)
	err := c.cc.Invoke(ctx, "/billingReaderPb.BillingReader/ReadReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingReaderServer is the server API for BillingReader service.
// All implementations must embed UnimplementedBillingReaderServer
// for forward compatibility
type BillingReaderServer interface {
	ReadReceipt(context.Context, *ReadReceiptRequest) (*ReadReceiptResponse, error)
	mustEmbedUnimplementedBillingReaderServer()
}

// UnimplementedBillingReaderServer must be embedded to have forward compatible implementations.
type UnimplementedBillingReaderServer struct {
}

func (UnimplementedBillingReaderServer) ReadReceipt(context.Context, *ReadReceiptRequest) (*ReadReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadReceipt not implemented")
}
func (UnimplementedBillingReaderServer) mustEmbedUnimplementedBillingReaderServer() {}

// UnsafeBillingReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingReaderServer will
// result in compilation errors.
type UnsafeBillingReaderServer interface {
	mustEmbedUnimplementedBillingReaderServer()
}

func RegisterBillingReaderServer(s grpc.ServiceRegistrar, srv BillingReaderServer) {
	s.RegisterService(&BillingReader_ServiceDesc, srv)
}

func _BillingReader_ReadReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingReaderServer).ReadReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billingReaderPb.BillingReader/ReadReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingReaderServer).ReadReceipt(ctx, req.(*ReadReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingReader_ServiceDesc is the grpc.ServiceDesc for BillingReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billingReaderPb.BillingReader",
	HandlerType: (*BillingReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadReceipt",
			Handler:    _BillingReader_ReadReceipt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/billing_reader.proto",
}
